### PR TITLE
Make #'GROUP work on sequences

### PR DESCRIPTION
**Pull request by EuAndreh**
Moved `#'GROUP` from `list.lisp` to `sequence.lisp` and made it work with sequences.

The code that gets called when `#'GROUP` receives a list is the same.

Moved the tests for group to `sequence-test.lisp` and added tests for sequences.

### CODE REVIEW

**Comment by EuAndreh** [comment]
Maybe even remove the `ETYPECASE` and let all fall into the `DO` form...

**Comment by vseloved** [comment]
Sorry, did I miss this PR?

**Comment by EuAndreh** [comment]
Well, I think so.

**Comment by vseloved** [comment]
I see. Sorry once again.
I'll add the changes manually then.

**Comment by EuAndreh** [comment]
OK. 

As commented, I think the `ETYPECASE` and the `#'REC` function defined by `LABELS` should be removed: just let everything go to the `DO` form.

What do you think?

**Comment by vseloved** [comment]
It seems to be not very efficient to call `subseq` for lists in this loop, no?

**Comment by EuAndreh** [comment]
Hmm, that's true. Maybe that's why I did it this way.

Well, feel free to change it as you wish.

**Comment by vseloved** [comment]
OK, got it

**Pull request closed without merging**
